FROM saravanabalagi/dev:ubuntu20.04-cuda11.1-cudnn8-nvcc-py38-node14
LABEL MAINTAINER=Saravanabalagi

ARG MATLAB_RELEASE
ARG LICENSE_USERNAME

# install deps
RUN apt-get update && apt-get install -y \
ca-certificates \
lsb-release \
libasound2 \
libatk1.0-0 \
libc6 \
libcairo2 \
libcap2 \
libcomerr2 \
libcups2 \
libdbus-1-3 \
libfontconfig1 \
libgconf-2-4 \
libgcrypt20 \
libgdk-pixbuf2.0-0 \
libgssapi-krb5-2 \
libgstreamer-plugins-base1.0-0 \
libgstreamer1.0-0 \
libgtk2.0-0 \
libk5crypto3 \
libkrb5-3 \
libnspr4 \
libnspr4-dev \
libnss3 \
libpam0g \
libpango-1.0-0 \
libpangocairo-1.0-0 \
libpangoft2-1.0-0 \
libselinux1 \
libsm6 \
libsndfile1 \
libudev1 \
libx11-6 \
libx11-xcb1 \
libxcb1 \
libxcomposite1 \
libxcursor1 \
libxdamage1 \
libxext6 \
libxfixes3 \
libxft2 \
libxi6 \
libxmu6 \
libxrandr2 \
libxrender1 \
libxslt1.1 \
libxss1 \
libxt6 \
libxtst6 \
libxxf86vm1 \
procps \
xkb-data \
xvfb \
x11vnc \
xvfb \
sudo \
zlib1g \
gcc g++ gfortran \
libgstreamer1.0-0 \
gstreamer1.0-tools \
gstreamer1.0-libav \
gstreamer1.0-plugins-base \
gstreamer1.0-plugins-good \
gstreamer1.0-plugins-bad \
gstreamer1.0-plugins-ugly \
gstreamer1.0-doc

# copy files
ADD matlab-install /matlab-install/
ADD matlab_installer_input.txt /matlab-install/matlab_installer_input.txt

# install matlab
RUN cd /matlab-install && \
    chmod +x ./install && \
    ./install -mode silent \
        -inputFile matlab_installer_input.txt \
        -outputFile /tmp/mlinstall.log \
    ; EXIT=$? && cat /tmp/mlinstall.log && test $EXIT -eq 0 \
    && rm -rf /matlab-install/

# add license
ADD license.lic /usr/local/MATLAB/$MATLAB_RELEASE/licenses/

# add a script to start MATLAB and soft link into /usr/local/bin
ADD startmatlab.sh /usr/local/bin/matlab_shell
RUN chmod +x /usr/local/bin/matlab_shell && \
    ln -s /usr/local/MATLAB/$MATLAB_RELEASE/bin/matlab /usr/local/bin/matlab && \
    ln -s /usr/local/MATLAB/$MATLAB_RELEASE/bin/mex /usr/local/bin/mex

# clean up after apt-get
RUN apt-get clean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

# setup mex
RUN mex -v -setup C++

# add user and make root
RUN useradd -ms /bin/bash $LICENSE_USERNAME
USER $LICENSE_USERNAME
WORKDIR /home/$LICENSE_USERNAME

# install poetry for user
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
ENV PATH="${PATH}:/home/${LICENSE_USERNAME}/.local/bin"
RUN poetry config virtualenvs.in-project true

# splash
CMD echo $(python --version) "($(which python))" && \
  echo $(poetry --version) "($(which poetry))" && \
  CUDA_PATH=$(whereis cuda | awk '{print($2)}') && echo "CUDA $CUDA_VERSION ($CUDA_PATH -> $(readlink $CUDA_PATH))" && \
  CUDNN_PATH=$(whereis libcudnn.so. | awk '{print($2)}') && echo "cuDNN $CUDNN_VERSION ($CUDNN_PATH -> $(readlink $CUDNN_PATH))" && \
  echo "" && \
  nvcc --version && \
  echo "" && \
  matlab -r quit -nojvm | grep "R2[0-9]*[ab]\|[[:space:]][MATLAB]" | sed 's/^ *//g' && \
  echo "Use matlab_shell to start" && \
  echo "" && \
  /bin/bash
